name: Test CIBW

on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: |
          pipx run build --sdist

      - name: Check metadata
        run: |
          pipx run twine check dist/*
          realpath dist/*

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  build_wheels:
    name: Wheels on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels to the project's github page
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
      
  test_wheels:
    name: Test wheels
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Check wheels
        run: ls -al dist

      - name: Install ABESS
        run: |
          python -m pip install --upgrade pip
          # pip install dist/
      
      - name: Test
        run: ls -al .
